<?php

/***************************************************************
 * Extension Manager/Repository config file for ext: "t3readspeaker"
 *
 * Auto generated by Extension Builder 2016-10-10
 *
 * Manual updates:
 * Only the data in the array - anything else is removed by next write.
 * "version" and "dependencies" must not be touched!
 ***************************************************************/

$EM_CONF[$_EXTKEY] = array(
	'title' => 'Readspeaker for TYPO3',
	'description' => 'Integrate the readspeaker service to your website. Provides 30+ Languages, 50+ Voices, easy to use',
	'category' => 'template',
	'author' => 'Salvatore Eckel',
	'author_email' => 'salvaracer@gmx.de',
	'state' => 'stable',
	'internal' => '',
	'uploadfolder' => '0',
	'createDirs' => '',
	'clearCacheOnLoad' => 1,
	'version' => '1.2.0',
	'constraints' => array(
		'depends' => array(
			'typo3' => '7.6.0-7.6.99',
		),
		'conflicts' => array(
		),
		'suggests' => array(
			'typoscript2ce' => '1.0.0-1.1.99',
		),
	),
);